"""empty message

Revision ID: 6a93a3640b40
Revises: 16bae015873d
Create Date: 2020-12-22 19:54:13.762758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a93a3640b40'
down_revision = '16bae015873d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Genres',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Venue_id', sa.Integer(), nullable=True),
    sa.Column('genre', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['Venue_id'], ['Venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Genres')
    # ### end Alembic commands ###
